{{- define "hosts.keycloak" -}}
{{ printf "%s.%s" .Values.subdomains.keycloak .Values.domain }}
{{- end -}}
{{- define "urls.keycloak" -}}
{{ printf "https://%s" (include "hosts.keycloak" .) }}
{{- end -}}

{{- define "urls.idp" -}}
{{ printf "https://%s/realms/master" (include "hosts.keycloak" .) }}
{{- end -}}
{{- define "urls.idp_saml_entrypoint" -}}
{{ printf "%s/protocol/saml" (include "urls.idp" .) }}
{{- end -}}

{{- define "hosts.authproxy" -}}
{{ printf "%s.%s" .Values.subdomains.oauth2_proxy .Values.domain }}
{{- end -}}
{{- define "urls.authproxy_login" -}}
{{ printf "https://%s/oauth2/start" (include "hosts.authproxy" .) }}
{{- end -}}
{{- define "urls.authproxy_logout" -}}
{{ printf "https://%s/oauth2/sign_out" (include "hosts.authproxy" .) }}
{{- end -}}
{{- define "urls.authproxy_check" -}}
{{ printf "https://%s/oauth2/auth" (include "hosts.authproxy" .) }}
{{- end -}}

{{- define "hosts.phpldapadmin" -}}
{{ printf "%s.%s" .Values.subdomains.phpldapadmin .Values.domain }}
{{- end -}}

{{- define "dn.base" -}}
{{ printf "dc=%s" (.Values.domain | splitList "." | join ",dc=") }}
{{- end -}}
{{- define "dn.users" -}}
{{ printf "ou=users,dc=%s" (.Values.domain | splitList "." | join ",dc=") }}
{{- end -}}
{{- define "dn.groups" -}}
{{ printf "ou=groups,dc=%s" (.Values.domain | splitList "." | join ",dc=") }}
{{- end -}}
{{- define "dn.roles" -}}
{{ printf "ou=roles,dc=%s" (.Values.domain | splitList "." | join ",dc=") }}
{{- end -}}
{{- define "dn.admin" -}}
{{ printf "cn=admin,dc=%s" (.Values.domain | splitList "." | join ",dc=") }}
{{- end -}}

{{- define "class.users" -}}
inetOrgPerson
{{- end -}}
{{- define "class.groups" -}}
groupOfNames
{{- end -}}
{{- define "class.roles" -}}
groupOfNames
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configSecretName }}
type: Opaque
data:
  idp_url: {{ include "urls.idp" . | b64enc }}
  idp_cert_secret: {{ "idp-cert" | b64enc }}

  admin_group: {{ .Values.admin.group | b64enc }}
  admin_email: {{ .Values.admin.email | b64enc }}

  oidc_issuer_url: {{ include "urls.idp" .  | b64enc }}
  saml_entrypoint_url: {{ include "urls.idp_saml_entrypoint" . | b64enc }}

  ldap_host: {{ printf "openldap.%s.svc.cluster.local" .Release.Namespace | b64enc }}
  ldap_port: {{ "389" | b64enc }}
  ldap_base_dn: {{ include "dn.base" . | b64enc }}
  ldap_admin_dn: {{ include "dn.admin" . | b64enc }}
  ldap_admin_pw: {{ include "common.secrets.passwords.manage" (dict "secret" .Values.configSecretName "key" "ldap_admin_pw" "providedValues" (list "") "context" $) }}
  ldap_users_dn: {{ include "dn.users" . | b64enc }}
  ldap_groups_dn: {{ include "dn.groups" . | b64enc }}
  ldap_roles_dn: {{ include "dn.roles" . | b64enc }}
  ldap_users_class: {{ include "class.users" . | b64enc }}
  ldap_groups_class: {{ include "class.groups" . | b64enc }}
  ldap_roles_class: {{ include "class.roles" . | b64enc }}

  authproxy_login_url: {{ include "urls.authproxy_login" . | b64enc }}
  authproxy_logout_url: {{ include "urls.authproxy_logout" . | b64enc }}
  authproxy_check_url: {{ include "urls.authproxy_check" . | b64enc }}
  authproxy_cookie_secret: {{ include "common.secrets.passwords.manage" (dict "secret" .Values.configSecretName "key" "authproxy_cookie_secret" "providedValues" (list "") "length" 16 "context" $) }}

  keycloak_url: {{ include "urls.keycloak" . | b64enc }}
  keycloak_admin_user: {{ "admin" | b64enc }}
  keycloak_admin_pw: {{ include "common.secrets.passwords.manage" (dict "secret" .Values.configSecretName "key" "keycloak_admin_pw" "providedValues" (list "") "context" $) }}

  internal_oidc_client_id: {{ "authproxy-oidc" | b64enc }}
  internal_oidc_client_secret: {{ include "common.secrets.passwords.manage" (dict "secret" .Values.configSecretName "key" "internal_oidc_client_secret" "providedValues" (list "") "context" $) }}
