apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
spec:
  interval: 5m
  chart:
    spec:
      chart: oauth2-proxy
      version: '6.2.0'
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
  dependsOn:
    - name: keycloak-config
  valuesFrom:
    - kind: Secret
      name: {{ .Values.configSecretName }}
      valuesKey: internal_oidc_client_secret
      targetPath: "config.clientSecret"
  values:
    config:
      clientID: {{ include "names.oidc_client" . }}
      clientSecret: ""
      cookieSecret: {{ randAlphaNum 32 }}
      configFile: |-
        upstreams = "file:///dev/null"
        whitelist_domains = [ {{ printf ".%s" .Values.domain | quote }} ]
        provider = "oidc"
        provider_display_name = {{ printf "SSO for %s" .Values.domain | quote }}
        oidc_issuer_url = {{ include "urls.idp" . | quote }}
        redirect_url = {{ include "urls.authproxy_callback" . | quote }}
        set_xauthrequest = true
        set_authorization_header = true
        pass_authorization_header = true
        pass_access_token = true
        cookie_samesite = "none"
        cookie_domains = [ {{ printf ".%s" .Values.domain | quote }} ]
        email_domains = "*"
        scope = "email groups profile openid"
        {{ if .Values.test_run -}}
        ssl_insecure_skip_verify = true
        {{- end }}
    # -> see https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#config-file
    # and https://dexidp.io/docs/custom-scopes-claims-clients/#scopes
    # and https://dexidp.io/docs/custom-scopes-claims-clients/#cross-client-trust-and-authorized-party
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: acme
      hosts:
        - {{ include "hosts.authproxy" . }}
      tls:
        - hosts:
            - {{ include "hosts.authproxy" . }}
          secretName: oauth2-proxy-cert
