apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap
spec:
  interval: 5m
  chart:
    spec:
      chart: openldap-stack-ha
      version: '3.0.0'
      sourceRef:
        kind: HelmRepository
        name: helm-openldap
  valuesFrom:
    - kind: Secret
      name: {{ .Values.configSecretName }}
      valuesKey: ldap_admin_pw
      targetPath: "global.adminPassword"
    - kind: Secret
      name: {{ .Values.configSecretName }}
      valuesKey: ldap_admin_pw
      targetPath: "global.configPassword"
  values:
    customTLS:
      enabled: false
    replicaCount: 1
    global:
      ldapDomain: {{ .Values.domain }}
    env:
      LDAP_ORGANISATION: {{ .Values.org.name | quote }}
    customFileSets:
      - name: bootstrap-ldif
        targetPath: /container/service/slapd/assets/config/bootstrap/ldif
        files:
          - filename: ous.ldif
            content: |
              dn: {{ include "dn.users" . }}
              objectClass: organizationalUnit
              ou: users

              dn: {{ include "dn.groups" . }}
              objectClass: organizationalUnit
              ou: groups

              dn: {{ include "dn.roles" . }}
              objectClass: organizationalUnit
              ou: roles
    ltb-passwd:
      enabled: false
    phpldapadmin:
      env:
        PHPLDAPADMIN_HTTPS: "false"
      ingress:
        {{ $phpldapadmin_host := printf "%s.%s" .Values.subdomains.phpldapadmin .Values.domain -}}
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: acme
        hosts:
          - {{ $phpldapadmin_host }}
        tls:
          - hosts:
              - {{ $phpldapadmin_host }}
            secretName: phpldapadmin-cert