domain: "" # The public root domain of this cluster (e.g. "example.org")

org:
  name: "" # The full name of your organization
  defaultLocale: "en_US"
  logoURL: ""

admin:
  idp:
    # See https://dexidp.io/docs/connectors/
    type: "github"
    clientID: ""
    clientSecret: ""
    issuerURL: ""
  group: "" # A label identifying the group provided by your IDP, which is to be granted admin privileges (org:team for GitHub)
  email: "" # Admin email address (for email notifications and initial admin accounts)

subdomains:
  # Under which subdomains of your supplied root domain should the various services run? (Created automatically by external-dns)
  keycloak: "idp"
  dex: "oidc"
  oauth2_proxy: "auth"
  phpldapadmin: "ldap"

repo:
  url: "https://github.com/lorenzo-w/domain-sso"
  branch: "main"

configSecretName: sso-config # Where to store generated SSO config values (overridden, if exists)
