apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
spec:
  interval: 5m
  chart:
    spec:
      chart: oauth2-proxy
      version: '6.2.0'
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
  dependsOn:
    - name: keycloak-config
  values:
    config:
      clientID: authproxy-oidc
      clientSecret: {{ include "get_sso_config" (dict "key" "internal_oidc_client_secret" "context" $) }}
      cookieSecret: {{ randAlphaNum 32 }}
      configFile: |-
        upstreams = "file:///dev/null"
        whitelist_domains = [ {{ printf ".%s" .Values.domain | quote }} ]
        provider = "oidc"
        provider_display_name = {{ printf "SSO for %s" .Values.domain | quote }}
        oidc_issuer_url = {{ include "get_sso_config" (dict "key" "oidc_issuer_url" "context" $) | quote }}
        redirect_url = {{ include "urls.authproxy_callback" . | quote }}
        set_xauthrequest = true
        set_authorization_header = true
        pass_authorization_header = true
        pass_access_token = true
        cookie_samesite = "none"
        cookie_domains = [ {{ printf ".%s" .Values.domain | quote }} ]
        email_domains = "*"
        scope = "email groups profile openid"
    # -> see https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#config-file
    # and https://dexidp.io/docs/custom-scopes-claims-clients/#scopes
    # and https://dexidp.io/docs/custom-scopes-claims-clients/#cross-client-trust-and-authorized-party
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: acme
      hosts:
        - {{ .Values.hosts.oauth2_proxy }}
      tls:
        - hosts:
            - {{ .Values.hosts.oauth2_proxy }}
          secretName: oauth2-proxy-cert
