apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "common.names.fullname" . }}
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak-config-cli
      version: '1.2.3'
      sourceRef:
        kind: HelmRepository
        name: jkroepke
  values:
    image:
      tag: "5.2.0-18.0.0"
    env: 
      KEYCLOAK_URL: {{ include "get_sso_config" (dict "key" "keycloak_url" "context" $) }}
      KEYCLOAK_USER: {{ include "get_sso_config" (dict "key" "keycloak_admin_user" "context" $) }}
      IMPORT_FILES_LOCATIONS: "/config/master.json"
      IMPORT_MANAGED_CLIENT: "no-delete" # Do not delete existing clients, just add new ones
    secrets:
      KEYCLOAK_PASSWORD: {{ include "get_sso_config" (dict "key" "keycloak_admin_pw" "context" $) }}
    config: 
      master:
        inline:
          enabled: true
          realm: master
          clients: 
            {{ range $client := .Values.clients.oidc -}}
            - clientId: {{ $client.id }}
              name: {{ $client.id }}
              description: "Internal OIDC client"
              enabled: true
              clientAuthenticatorType: client-secret
              secret: {{ (lookup "v1" "Secret" $.Release.Namespace $client.secretName).data.secret | b64dec | quote }}
              redirectUris: 
              {{ range $uri := $client.redirectURIs -}}
                - {{ $uri }}
              {{ end -}}
              webOrigins: 
                - "*"
              defaultClientScopes:
                - email
                - profile
              optionalClientScopes:
                - groups
                - roles
            {{ end -}}
            {{ range $client := .Values.clients.saml -}}
            - clientId: {{ $client.id }}
              protocol: saml
              name: {{ $client.id }}
              description: "Internal SAML client"
              enabled: true
              rootUrl: {{ $client.rootURL }}
              redirectUris: 
                - "*"
              webOrigins: 
                - "*"
              frontchannelLogout: true
              attributes:
                {{ $secretData := (lookup "v1" "Secret" $.Release.Namespace $client.certSecretName).data -}}
                saml.signing.private.key: {{ index $secretData "tls.key" | b64dec | quote }}
                saml.signing.certificate: {{ index $secretData "tls.crt" | b64dec | quote }}
                saml.force.post.binding: "false"
                saml.signature.algorithm: RSA_SHA256
                saml.assertion.signature: "true"
                saml_name_id_format: email
                {{ if eq $client.assertionConsumer.method "post" -}}
                saml_assertion_consumer_url_post: {{ $client.assertionConsumer.url }}
                {{ end -}}
                {{ if eq $client.assertionConsumer.method "redirect" -}}
                saml_assertion_consumer_url_redirect: {{ $client.assertionConsumer.url }}
                {{ end -}}
                {{ if eq $client.logoutService.method "post" -}}
                saml_single_logout_service_url_post: {{ $client.logoutService.url }}
                {{ end -}}
                {{ if eq $client.logoutService.method "redirect" -}}
                saml_single_logout_service_url_redirect: {{ $client.logoutService.url }}
                {{- end }}

              protocolMappers:
                - name: firstName
                  protocol: saml
                  protocolMapper: saml-user-attribute-mapper
                  config:
                    attribute.nameformat: Basic
                    user.attribute: firstName
                    attribute.name: cn
            {{ end -}}
